options = [
    "Team", 
    "Decade", 
    "Teammate", 
    "Points career", 
    "Assists career", 
    "Rebounds career", 
    "Steals career", 
    "Blocks career", 
    "Games career", 
    "PPG season", 
    "AST per game season", 
    "REB per game season", 
    "STL per game season", 
    "BLK per game season", 
    "Points game", 
    "Assists game", 
    "Rebounds game", 
    "Steals game", 
    "Blocks game", 
    "Drafted before", 
    "Drafted after", 
    "All-Star", 
    "All-NBA", 
    "All-Defensive", 
    "All-Rookie"
    ]